name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:
    name: Run Integration Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dpendencies
      run: npm ci --legacy-peer-deps
    
    - name: Run lint
      run: npm run lint
    
    - name: Run Testing
      run: npm test
